#!/bin/zsh

## General ZSH settings

# Moar fancy globs
setopt EXTENDEDGLOB

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=$HISTSIZE
setopt HIST_IGNORE_SPACE
setopt HIST_IGNORE_ALL_DUPS

autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Input
bindkey -v

source /etc/zsh/$TERM

bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
[[ -n ${key[Up]} ]] && bindkey "${key[Up]}" up-line-or-beginning-search
[[ -n ${key[Down]} ]] && bindkey "${key[Down]}" down-line-or-beginning-search
[[ -n ${key[Home]} ]] && bindkey -a "${key[Home]}" beginning-of-line
[[ -n ${key[End]} ]] && bindkey -a "${key[End]}" end-of-line
[[ -n ${key[Delete]} ]] && bindkey -a "${key[Delete]}" delete-char
[[ -n ${key[Insert]} ]] && bindkey -a "${key[Insert]}" vi-insert
[[ -n ${key[Backspace]} ]] && bindkey -a "${key[Backspace]}" backward-delete-char
[[ -n ${key[Home]} ]] && bindkey -v "${key[Home]}" beginning-of-line
[[ -n ${key[End]} ]] && bindkey -v "${key[End]}" end-of-line
[[ -n ${key[Delete]} ]] && bindkey -v "${key[Delete]}" delete-char
[[ -n ${key[Insert]} ]] && bindkey -v "${key[Insert]}" vi-insert
[[ -n ${key[Backspace]} ]] && bindkey -v "${key[Backspace]}" backward-delete-char

# Prompt
autoload -Uz promptinit
promptinit
setopt PROMPT_SUBST

prompt gentoo

# Autocompletion
autoload -Uz compinit
compinit

zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric
zstyle ':completion:*' prompt ''\'':completion:*:descriptions'\'' format '\''%U%B%d%b%u'\'' '
zstyle :compinstall filename '~/.zshrc'

## Aliases

# Faster jumping upwards a few levels in directories
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"
# URL encoding and decoding
alias urldecode='python -c "import sys; from urllib import parse as ulp; print(ulp.unquote_plus(sys.argv[1]))"'
alias urlencode='python -c "import sys; from urllib import parse as ulp; print(ulp.quote_plus(sys.argv[1]))"'
# Color my diffs
alias diff=colordiff
# Syntax highlighted less
alias lessc='LESSOPEN="| /usr/bin/src-hilite-lesspipe.sh %s" less -M '
# Colos ls
alias ls='ls --color=auto'
# Easy detailed listing
alias ll='ls -la'
# Color grep
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
# Smart case for rg
alias rg='rg -S'

## Functions

# Print exit code of last command it it was non zero
function prompt-show-status ()
{
  # Don't use `status'.  It's read-only in zsh.
  local stat="$?"

  if test $stat -ne 0 -a $stat != 128; then
    # If process exited by a signal, determine name of signal.
    if test $stat -gt 128; then
      local signal="$(builtin kill -l $[$stat - 128] 2>/dev/null)"
      test "$signal" && signal=" ($signal)"
    fi
    echo -e "\033[01;31m[Exit $stat$signal]\033[00m" 1>&2
  fi
  test "$BASH" && history -a
  return 0
}

# Quickly back up files
bak() {
    [[ $# < 1 ]] && exit 0
    while [[ $# > 0 ]] ; do
        cp "${1}" "${1}~"
        shift
    done
}

## Other stuff

# mc exit to current directory
source /usr/libexec/mc/mc.sh
