#!/bin/sh
#
# cmus-status-display
#
# Usage:
#   in cmus command ":set status_display_program=cmus-status-display"
#
# This scripts is executed by cmus when status changes:
#   cmus-status-display key1 val1 key2 val2 ...
#
# All keys contain only chars a-z. Values are UTF-8 strings.
#
# Keys: status file url artist album discnumber tracknumber title date
#   - status (stopped, playing, paused) is always given
#   - file or url is given only if track is 'loaded' in cmus
#   - other keys/values are given only if they are available
#

output()
{
    notify-send -a cmus -i "${icon}" "♫♬" "<b><h1>${_status^}</h1></b>$*"
}

while test $# -ge 2
do
    eval _$1='$2'
    shift
    shift
done

if [[ -n "$_file" ]]
then
    # Compute duration time
    h=$(($_duration / 3600))
    m=$(($_duration % 3600))

    # Compose hh:mm duration string
    duration=""
    test $h -gt 0 && dur="$h:"
    duration="$dur$(printf '%02d:%02d' $(($m / 60)) $(($m % 60)))"

    icon="audio"
    # Check if there is an albumart and override default icon
    art="$(dirname "$_file")/folder.jpg"
    if [[ -f "$art" ]]
    then
        icon=$art
    fi

    output "<br>${_title}<br>${_album} (${_date})<br>by ${_artist}<br>${duration}"
elif test -n "${_url}"
then
    output "<br>${_url}<br>${_title}"
else
    output ""
fi
